### ISSUE TITLE
AML Context Lookup

### ISSUE THREAD

**Issue by ClemaX** [rust-osdev/acpi#115]
The documentation states that we can use something like
```
let my_aml_value = aml_context.lookup(&AmlName::from_str("\\_SB.PCI0.S08._ADR").unwrap());
```
to retrieve aml values, but when used, the compiler cannot find the method:
```
let result = context.lookup(&AmlName::from_str("\\_SB.PCI0.I2C0.TPDE").unwrap());
                     ^^^^^^ method not found in `AmlContext`
```

Is this method already implemented? If it is, are there other steps needed than calling AmlContext::new, parsing a table and calling lookup?

**Comment by IsaacWoods** [comment]
Ah apologies - the documentation is stale. Objects are now accessed through the [`Namespace` type](https://docs.rs/aml/0.16.1/aml/struct.Namespace.html):
``` rust
let my_aml_value = aml_context.namespace.get_by_path(&AmlName::from_str("\\_SB.PCI0.S08._ADR").unwrap()).unwrap();
```
`Namespace` also provides a [`search`](https://docs.rs/aml/0.16.1/aml/struct.Namespace.html#method.search) function that applies ACPI's recursive searching algorithm.

I will publish an update with corrected examples when I have the chance. Cheers for reporting!
