### ISSUE TITLE
AML: Support some real hardware platforms

### ISSUE THREAD

**Issue by kennystrawnmusic** [rust-osdev/acpi#122]
Managed to aggregate a few `acpi-dumper` outputs into a [database](https://github.com/kennystrawnmusic/acpi-dumper-db) that could easily be used as a starting point for the team — using this issue as a starting point for implementation based on what I found.

Direct links to dumps from the hardware in question:
* [Custom-built mining rig with MSI H310-F Pro motherboard, Coffee Lake i5-8400 CPU, and 6 Sapphire RX-480s](https://github.com/kennystrawnmusic/acpi-dumper-db/tree/main/msi-h310f-pro-miner-ellesmerex6) — this is the machine I'm actually doing kernel development on
* [Asus VivoBook E203M](https://github.com/kennystrawnmusic/acpi-dumper-db/tree/main/e203m)
* [Lenovo IdeaPad 110](https://github.com/kennystrawnmusic/acpi-dumper-db/tree/main/ideapad-110)

**Comment by kennystrawnmusic** [comment]
Added some disassembly to make it even easier for @IsaacWoods to solve this.

**Comment by IsaacWoods** [comment]
I'm afraid I do not have time to be trawling through the ACPI logs of hardware I do not own - it's one thing to curate + manage individual PRs for `x` or `y` not working (e.g. this opcode isn't supported, or does the wrong thing for this reduced testcase), and quite another to be given a 20kb DSDT with the issue of "this doesn't work yet".

If you'd like to run the parser yourself over these and make individual issues with small testcases, that's more than welcome.

A second note: mine + the project's position is that we are not maintaining and can't condone open databases of firmware dumps. None of us are lawyers (afaik), and we're not sure how these dumps interact with relevant copyright and other applicable law, or the EULAs for the products themselves. This obviously sucks, but I and others have professional registrations to consider, so I have to take a risk-adverse approach to this. You are welcome, obviously, to make your own mind up about whether you're happy to do this, but I just thought I'd mention it.
