### ISSUE TITLE
Publishing a new version

### ISSUE THREAD

**Issue by scholzp** [rust-osdev/acpi#185]
Hi all,
when I was looking for a crate implementing certain ACPI functionality, I found this one to be useful but quickly noticed, that version 4.1.1 lacks some features I needed. I then cloned the repository to implement those on my own, only to find them already implemented in the `main` branch of this repository. I therefore wanted to ask, if we could get a new release of `acpi` and `rsdp`?

Thanks in advance!

**Comment by IsaacWoods** [comment]
Apologies for the lack of a reply on this; a new version of `acpi` has now been published, and `rsdp` deprecated in favour of new functionality in `acpi`!
