### ISSUE TITLE
from_rsdt missing

### ISSUE THREAD

**Issue by uglyoldbob** [rust-osdev/acpi#203]
What happened to the from_rsdt function?
It looks like it was removed with commit c0e45933de468f2afad117808fe342a3e8dfa7e6.

**Comment by Hsy-Intel** [comment]
Same concerns. I want to upgrade the acpi crate version in [this project](https://github.com/asterinas/asterinas). However, I can't find the `from_rsdt` interface [here](https://github.com/asterinas/asterinas/blob/main/ostd/src/arch/x86/kernel/acpi/mod.rs#L106-L111) if I use the latest acpi version. Any suggestions? @IsaacWoods Thanks~

**Comment by IsaacWoods** [comment]
This was indeed removed by #131 and wasn't picked up in review. I've been meaning to re-add it at some point but have not gotten around to it.

Thanks both for reporting and for the PR - this should be fixed as of #222. I will release a new version with this included when I get the chance.
