### ISSUE TITLE
Parsing ACPI Tables from RSDT

### ISSUE THREAD

**Issue by FilipToth** [rust-osdev/acpi#224]
I am using the `multiboot2` create to get the boot info. I can't directly get the RSDP address, but I can get the RSDT address from the `RsdpV1Tag` provided by the multiboot crate. I noticed in the docs that there *is supposed to be* a way to parse ACPI tables directly by providing the RSDT address, but couldn't find it in the source. Was this API removed? Are there currently any alternatives to providing the RSDP address in version `5.0.0`?

Thanks in advance.

**Comment by IsaacWoods** [comment]
Yes, the `from_rsdt` method was mistakenly removed from a previous version. It has recently been reimplemented - please update to `v5.1.0`.
