### ISSUE TITLE
Visibility of `aml::resource::IOPortDescriptor` members

### ISSUE THREAD

**Issue by pjhades** [rust-osdev/acpi#227]
Hello! I need the information provided by `aml::resource::IOPortDescriptor` to do some device initialization. But its members are all private and I don't see any interface for accessing them. Can we make them (along with the members of other descriptor structs) public, like in `aml::resource::IrqDescriptor`? If that sounds reasonable I can open a PR.

**Comment by IsaacWoods** [comment]
Yep I think all of these should be public - this seems like an oversight on our part. Please do open a PR!
