### ISSUE TITLE
Potential users: views on the API surface?

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#24]
@Restioson and I have been discussing the API surface for `acpi` for a while over on Gitter and think it'd be useful to get some insight from more potential users.

So far, we have come up with two options for relaying information to the user:
* Callbacks on `AcpiHandler`. This is a trait that allows the library to e.g. map physical memory into the virtual address space without knowing anything about the paging implementation, an implementation of which is provided by the user. This would be extended with methods such as `register_processor` which would be called as we parse the tables.
* Return a struct `Acpi` (this currently exists but was meant to be internal to the library) that contains all the information gained from parsing the tables. This is likely to be large to keep around (for example, it will contain the entire AML namespace). This structure will also provide methods to interact with the ACPI context after parsing, such as executing control methods, changing global power state etc.

The key issue here is knowing how much information we want to provide, and in what format. I'm assuming most people won't care about the implementation details and don't want to read the ACPI spec, and so want a high-level overview that just allows them to get the information they need, but I would appreciate some feedback about this.

Writing this out, I am starting to strongly favour the second approach, as I believe it is more flexible from the perspective of the OS/user, but it'd be good to get some more opinions.

cc @rust-osdev/all

**Comment by lachlansneff** [comment]
Yeah, I'm honestly tired of using trait callbacks in libraries in rust, so I'd prefer the second option on that basis. Other than that, I don't care.

**Comment by Restioson** [comment]
I don't really mind which system (push based or pull based) at the moment.

I do think that we should have a way to access the low level, bare acpi information as well as a higher level wrapper around it. Thoughts?

**Comment by IsaacWoods** [comment]
I'll take silence as consensus on the second method :)

On access to the raw tables - I'm not sure it offers users much advantage. If they can't do something they want to, that's a deficiency in the higher-level API, and it may make the API surface much bigger to expose all the types involved in the internal representations. What do you imagine needing the bare information for?
