### ISSUE TITLE
Provide function to get the preferred PM profile

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#29]
This is meant as an easy first issue to get familiar with the library's workings. We should provide a way for the user to get the preferred Power Management profile from the FADT.

To do this, we should:
1) Add an enum called `PowerManagementProfile` with the correct variants (read section 5.2.9 of the ACPI spec for a hint here)
2) In `parse_fadt`, match against the `preferred_pm_profile` field of the FADT and turn it into a `PowerManagementProfile`
3) Add a field `preferred_pm_profile` in the root `Acpi` struct and set it in `parse_fadt`
4) Add a getter to `Acpi` to return this field

**Comment by IsaacWoods** [comment]
Yeah, that type name is uhh... long.

However, I'm not keen on the abbreviation. How about `PowerManagementProfile` or even just `PowerProfile`

**Comment by Restioson** [comment]
Yep either of those work.
