### ISSUE TITLE
Replace use of typenum in ExtendedField with const generics

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#44]
At the moment, we use `typenum` to provide type-level numbers to use in `ExtendedField`. We should be able to replace this with const generics now or in the near future, which should be neater and get rid of a dependency.

**Comment by Restioson** [comment]
Yay! Const-generics!!

**Comment by 64** [comment]
Also this: https://github.com/rust-osdev/acpi/blob/master/aml_parser/src/parser.rs#L165

(may be other places)
