### ISSUE TITLE
Record attempted conversion in AmlError::IncompatibleValueConversion

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#53]
- Include the current and target types in the error type (e.g. `IncompatibleValueConversion(AmlType, AmlType)`).
- Convert all places where the error is emitted to fill in the correct types (these will be able to be hardcoded for most conversions).

**Comment by KnapSac** [comment]
I'd like to give this a shot.

**Comment by IsaacWoods** [comment]
Great, let me know if you have any questions!

**Comment by KnapSac** [comment]
I have a few, I left them in my PR (#90).

**Comment by IsaacWoods** [comment]
Closed by #90
