### ISSUE TITLE
Provide way to easily dump host's ACPI tables

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#55]
On Linux, it looks like the kernel provides the raw ACPI table data in the `sys` filesystem at the paths: `/sys/firmware/acpi/tables/{SIGNATURE (e.g. MCFG)}`. This should make it fairly easy on Linux to get all the tables a platform has. Similar mechanisms might be present on Windows, if we want to extend to supporting that.

We also want to collect information about the platform, such as CPU model (maybe just the entire output of `lshw`?). We should give user's a chance to easily check what info they'd be contributing, to make it easy for people to make sure no sensitive data ends up in our test suite.

We then want to construct an entry in whatever format the integration tests end up in, allowing the test runner to test a wide variety of hardware. This makes it easy to contributors to simply dump their platform's tables, commit to their fork, and then make a pull-request.

Both reading from the `/sys` filesystem and running `lshw` need root access, so this would
unfortunately have to be run with sudo. Hopefully that wouldn't put too many people off, and they can always vet the code of the dumper themselves.

**Comment by 64** [comment]
ACPICA contains some tools for dumping AML (specifically, the `acpidump` command). This works on Windows too, so we can probably write a small wrapper script around this to do what we want

**Comment by 64** [comment]
Windows stores ACPI tables in the registry under `HKLM\HARDWARE\ACPI`, it seems. As for a `lshw` replacement, there's [DevCon](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon) but it might be a pain if we require users to install it.

**Comment by IsaacWoods** [comment]
This is now provided by the `acpi_dumper` utility on Linux.
