### ISSUE TITLE
MCFG parsing: entry length assertion failed

### ISSUE THREAD

**Issue by fuchsnj** [rust-osdev/acpi#58]
While parsing the `MCFG` table, [the entry length assertion](https://github.com/rust-osdev/acpi/blob/master/acpi/src/mcfg.rs#L46) fails on one of my test devices (Dell Inspiron 1420 laptop).

An MCFG entry looks like it's supposed to be 16 bytes long. My test device reports a length of 62 bytes for the MCFG table, and after subtracting the header (36 bytes) + reserved area (8 bytes) that leaves exactly 18 bytes left, instead of the expected 16, so the assertion fails. The only thing odd I noticed is that the revision is 16 (my other test device that works correctly is revision 1). It looks like the data is valid if you only parse the first 16, so it might be good to remove the assertion and just let it round down. I couldn't find any documentation for that specific version.

Here is the raw entry data if that helps at all (in base 10)
`[0,0,0,244,0,0,0,0,0,0,0,63,0,0,0,0,0,0]`

**Comment by IsaacWoods** [comment]
Note to self: it might be nice to collect descriptions of all the bugs like this we find and the platforms that are affected.
