### ISSUE TITLE
Parsing PREFIX_CHAR is unimplemented!()

### ISSUE THREAD

**Issue by trashbyte** [rust-osdev/acpi#66]
I'm working on a kernel using the acpi and aml crates, and the tables generated by QEMU contain parent prefix paths, which currently cause a panic since handling `PREFIX_CHAR` in `name_string()` is `unimplemented!()` (name_object.rs 73:28). Right now this is keeping me from being able to do much of anything with acpi tables. I fiddled around with it a bit trying to find a workaround but I couldn't get it to parse successfully. If you aren't planning on implementing it soon, I'd appreciate having a way to ignore those entries and continue parsing, or something like that.

**Comment by IsaacWoods** [comment]
This should be fixed when #67 merges, after which I'll publish the crates as `v0.7.0`.

I'd be interested to see how you're invoking QEMU, as the library has been tested on it fairly thorougly and I've never seen it produce a `NameString` that actually uses a prefix char?
