### ISSUE TITLE
make the Fadt public

### ISSUE THREAD

**Issue by JCapucho** [rust-osdev/acpi#85]
Right now the `acpi` crate doesn't expose the `Fadt` table and instead picks some information from it, but somethings that are necessary for the operation of the acpi cannot be gathered without the user redefining the `Fadt` themselves.

I have a local copy of the repository with some `Fadt` fields public and re exporting it as public, if it's of interest i can make a PR with it.

**Comment by IsaacWoods** [comment]
Thanks for raising this! It's not really a design choice of the library not to have these things available, more just a lack of it being done.

I'm not aversed to making the table types available, but I'd like the chance to look over each one before doing so as they'll become part of the stable API. Some of the fields of the FADT should not become public themselves, but should instead be exposed through methods that check for the presence of the extended field.

I should hopefully have some time to work on this at some point this week.
