### ISSUE TITLE
Support new MADT Multiprocessor Wakeup structures

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#87]
ACPI v6.4 introduces a new mechanism for waking up APs, using some sort of mailbox defined in the MADT. We should support and expose these new entries.

**Comment by wusyong** [comment]
Hello, I would like to give it a shot. Is there any reference I could look into?

**Comment by IsaacWoods** [comment]
Hi; great to hear! Yes - the best place to start would be look at [our existing code for MADT entries](https://github.com/rust-osdev/acpi/blob/master/acpi/src/madt.rs), and then the spec for the structure of the new entries (make sure to grab the v6.4 version from [this page](https://uefi.org/specifications), as these are very new).
